config/routes.rb
TestApp::Application.routes.draw do

  mount RailsAdmin::Engine => '/admin', :as => 'rails_admin'

  devise_for :users

  resources :products

  resources :orders

  resources :users do
    member do
      resource :cart, controller: 'UserCart'
    end
  end

  resources :products do
    member do
      get :add_to_cart
    end
  end

  resources :orders do
    member do
      get :remove_from_cart
    end
  end

  resources :carts

  root :to => 'static#welcome'

  match '/about(.:format)', :to => 'static#about'
  match '/contact(.:format)', :to => 'static#contact'
end

app/models/product.rb
class Product < ActiveRecord::Base
	has_many :orders
	validates :name, :presence => true
	validates :price, :presence => true
	validates :price, :numericality => true
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController

  before_filter :redirect_if_nonadmin, :only => [:edit, :destroy]
  before_filter :authenticate_user!, :only => [:add_to_cart]

  def add_to_cart
    render :nothing => true
    @product = Product.find(params[:id])
    order = Order.create(:cart_id => current_user.cart.id, :product_id => @product.id, :quantity => 1)
    current_user.cart.orders.build params[order]
    #redirect_to products_path
  end

  # GET /products
  # GET /products.json
  def index
    @products = Product.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @products }
    end
  end

  # GET /products/1
  # GET /products/1.json
  def show
    @product = Product.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @product }
    end
  end

  # GET /products/new
  # GET /products/new.json
  def new
    @product = Product.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @product }
    end
  end

  # GET /products/1/edit
  def edit
    @product = Product.find(params[:id])
  end

  # POST /products
  # POST /products.json
  def create
    @product = Product.new(params[:product])

    respond_to do |format|
      if @product.save
        format.html { redirect_to @product, notice: 'Product was successfully created.' }
        format.json { render json: @product, status: :created, location: @product }
      else
        format.html { render action: "new" }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /products/1
  # PUT /products/1.json
  def update
    @product = Product.find(params[:id])

    respond_to do |format|
      if @product.update_attributes(params[:product])
        format.html { redirect_to @product, notice: 'Product was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /products/1
  # DELETE /products/1.json
  def destroy
    @product = Product.find(params[:id])
    @product.destroy

    respond_to do |format|
      format.html { redirect_to products_url }
      format.json { head :no_content }
    end
  end

  protected

  def redirect_if_nonadmin
    if !current_user || !is_admin?
      redirect_to :root
    end
  end
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/views/products/_form.html.erb
<%= form_for(@product, html: {class: "nice"}) do |f| %>
  <% if @product.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@product.errors.count, "error") %> prohibited this product from being saved:</h2>

      <ul>
      <% @product.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %>
    <%= f.text_field :name, class: 'input-text' %><br />
  </div>
  <div class="field">
    <%= f.label :description %>
    <%= f.text_field :description, class: 'input-text' %><br />
  </div>
  <div class="field">
    <%= f.label :price %>
    <%= f.text_field :price, class: 'input-text' %><br />
  </div>
  <div class="actions">
    <%= f.submit class: 'nice small radius button' %>
  </div>
<% end %>

app/views/products/edit.html.erb
<div class="container">
	<h1>Editing product</h1>

	<%= render 'form' %>

	<%= link_to 'Show', @product %> |
	<%= link_to 'Back', products_path %>
</div>

app/views/products/index.html.erb
<div class="container" style="padding: 0px">
  <h1>Listing Products</h1>

    <% @products.each_slice(3) do |product| %>
      <div class="row">
        <div class="four columns">
          <tr>
            <td><h5><%= product[0].name %></h5></td><br />
            <td><%= product[0].description %></td><br /><br />
            <td>$<%= product[0].price %></td><br />
            <td><%= link_to 'Show', product[0] %></td><br />
            <% if user_signed_in? %>
              <% if is_admin? %>
                <td><%= link_to 'Edit', edit_product_path(product[0]) %></td><br />
                <td><%= link_to 'Destroy', product[0], confirm: 'Are you sure?', method: :delete %></td><br />
              <% end %>
            <% end %>
            
              <td><%= link_to 'Add to Cart', add_to_cart_product_path(product[0]), :update => 'application/cart' %></td>
            
          </tr>
        </div>
        <% if product[1] %>
        <div class="four columns">
          <tr>
            <td><h5><%= product[1].name %></h5></td><br />
            <td><%= product[1].description %></td><br /><br />
            <td>$<%= product[1].price %></td><br />
            <td><%= link_to 'Show', product[1] %></td><br />
            <% if user_signed_in? %>
              <% if is_admin? %>
                <td><%= link_to 'Edit', edit_product_path(product[1]) %></td><br />
                <td><%= link_to 'Destroy', product[1], confirm: 'Are you sure?', method: :delete %></td><br />
              <% end %>
            <% end %>
            
              <td><%= link_to 'Add to Cart', add_to_cart_product_path(product[1]) %></td>
            
          </tr>
        </div>
        <% end %>
        <% if product[2] %>
        <div class="four columns">
          <tr>
            <td><h5><%= product[2].name %></h5></td><br />
            <td><%= product[2].description %></td><br /><br />
            <td>$<%= product[2].price %></td><br />
            <td><%= link_to 'Show', product[2] %></td><br />
            <% if user_signed_in? %>
              <% if is_admin? %>
                <td><%= link_to 'Edit', edit_product_path(product[2]) %></td><br />
                <td><%= link_to 'Destroy', product[2], confirm: 'Are you sure?', method: :delete %></td><br />
              <% end %>
            <% end %>
            
              <td><%= link_to 'Add to Cart', add_to_cart_product_path(product[2]) %></td>
            
          </tr>
        </div>
        <% end %>
      </div>
      <br />
      <br />
    <% end %>


  <br />

  <% if user_signed_in? %>
    <% if is_admin? %>
      <%= link_to 'New Product', new_product_path %>
    <% end %>
  <% end %>
</div>

app/views/products/new.html.erb
<h1>New product</h1>

<%= render 'form' %>

<%= link_to 'Back', products_path %>

app/views/products/show.html.erb
<div class="container">
	<p id="notice"><%= notice %></p>

	<p>
	  <b>Name:</b>
	  <%= @product.name %>
	</p>

	<p>
	  <b>Description:</b>
	  <%= @product.description %>
	</p>

	<p>
	  <b>Price:</b>
	  <%= @product.price %>
	</p>


	<%= link_to 'Edit', edit_product_path(@product) %> |
	<%= link_to 'Back', products_path %>
</div>